on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      # Run the steps we document in the Release Process.
      # unzip commands included as proof-of-life for the Carthage output.
      - run: |
          ruby --version
          echo -n "carthage version: " && carthage version
          echo -n "pod version: " && pod --version --verbose
          make --version
          make update
          make carthage_package
          unzip -l Ably.framework.zip
          unzip -l Ably.framework.zip | grep 'Mac/Ably.framework'
          unzip -l Ably.framework.zip | grep 'tvOS/Ably.framework'
          unzip -l Ably.framework.zip | grep 'iOS/Ably.framework'
          pod lib lint
