on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    uses: ably/ably-cocoa/.github/workflows/check-base.yml@feature/1273-one-job-per-workflow
    with:
      platform: tvOS
      lane: test_tvOS12
