on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    
    permissions:
      deployments: write
      id-token: write
      
    steps:
      - uses: actions/checkout@v2

      - name: Select Specific Xcode Version
        run: |
          sudo xcode-select -s /Applications/Xcode_13.2.app
          echo "Selected Xcode version:"
          xcodebuild -version

      - name: Build Documentation
        run: |
          bundle install
          ./Scripts/jazzy.sh
          ls -al Docs/jazzy

      - name: Upload Documentation
        uses: ably/sdk-upload-action@v1
        with:
          s3AccessKeyId: ${{ secrets.SDK_S3_ACCESS_KEY_ID }}
          s3AccessKey: ${{ secrets.SDK_S3_ACCESS_KEY }}
          sourcePath: Docs/jazzy
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          artifactName: jazzydoc
