name: "Integration Test: iOS 11"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    uses: ably/ably-cocoa/.github/workflows/integration-test.yaml@feature/1273-one-job-per-workflow
    with:
      lane: test_iOS11
