name: "Integration Test: iOS 12"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    uses: ably/ably-cocoa/.github/workflows/integration-test.yaml
    with:
      lane: test_iOS12
